steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg', 'NEXT_PUBLIC_SUPABASE_URL=$_NEXT_PUBLIC_SUPABASE_URL',
      '--build-arg', 'NEXT_PUBLIC_SUPABASE_ANON_KEY=$_NEXT_PUBLIC_SUPABASE_ANON_KEY',
      '--build-arg', 'NEXT_PUBLIC_SUPABASE_PROJECT_ALL_URL=$_NEXT_PUBLIC_SUPABASE_PROJECT_ALL_URL',
      '--build-arg', 'NEXT_PUBLIC_SUPABASE_PROJECT_ALL_ANON=$_NEXT_PUBLIC_SUPABASE_PROJECT_ALL_ANON',
      '--build-arg', 'NEXT_PUBLIC_SUPABASE_PROJECT_ALL_SCHEMA=$_NEXT_PUBLIC_SUPABASE_PROJECT_ALL_SCHEMA',
      '--build-arg', 'GEMINI_CLIENT_ID=$_GEMINI_CLIENT_ID',
      '--build-arg', 'GEMINI_API_KEY=$_GEMINI_API_KEY',
      '--build-arg', 'CLAUDE_API_KEY=$_CLAUDE_API_KEY',
      '--build-arg', 'GEMINI_CLIENT_SECRET=$_GEMINI_CLIENT_SECRET',
      '--build-arg', 'APS_CLIENT_ID=$_APS_CLIENT_ID',
      '--build-arg', 'APS_CLIENT_SECRET=$_APS_CLIENT_SECRET',
      '--build-arg', 'APS_CALLBACK_URL=$_APS_CALLBACK_URL',
      '-t', 'asia-southeast3-docker.pkg.dev/dwpaivibecode/pipeline-repo/pipeline-app:$BUILD_ID',
      '-t', 'asia-southeast3-docker.pkg.dev/dwpaivibecode/pipeline-repo/pipeline-app:latest',
      '.'
    ]

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast3-docker.pkg.dev/dwpaivibecode/pipeline-repo/pipeline-app:latest']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - '$_CLOUD_RUN_SERVICE'
    - '--image'
    - 'asia-southeast3-docker.pkg.dev/dwpaivibecode/pipeline-repo/pipeline-app:latest'
    - '--region'
    - 'asia-southeast3'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'GEMINI_CLIENT_ID=$_GEMINI_CLIENT_ID,GEMINI_CLIENT_SECRET=$_GEMINI_CLIENT_SECRET,GEMINI_API_KEY=$_GEMINI_API_KEY,CLAUDE_API_KEY=$_CLAUDE_API_KEY,NEXT_PUBLIC_SUPABASE_URL=$_NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY=$_NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_SUPABASE_PROJECT_ALL_URL=$_NEXT_PUBLIC_SUPABASE_PROJECT_ALL_URL,NEXT_PUBLIC_SUPABASE_PROJECT_ALL_ANON=$_NEXT_PUBLIC_SUPABASE_PROJECT_ALL_ANON,NEXT_PUBLIC_SUPABASE_PROJECT_ALL_SCHEMA=$_NEXT_PUBLIC_SUPABASE_PROJECT_ALL_SCHEMA,GOOGLE_CLOUD_PROJECT=dwpaivibecode,GOOGLE_CLOUD_LOCATION=asia-southeast3,APS_CLIENT_ID=$_APS_CLIENT_ID,APS_CLIENT_SECRET=$_APS_CLIENT_SECRET,APS_CALLBACK_URL=$_APS_CALLBACK_URL,GOOGLE_SERVICE_ACCOUNT_EMAIL=$_GOOGLE_SERVICE_ACCOUNT_EMAIL,GOOGLE_PRIVATE_KEY=$_GOOGLE_PRIVATE_KEY'

images:
  - 'asia-southeast3-docker.pkg.dev/dwpaivibecode/pipeline-repo/pipeline-app:latest'

substitutions:
    _CLOUD_RUN_SERVICE: 'dwp-pipeline-v2'
    _NEXT_PUBLIC_SUPABASE_URL: '' 
    _NEXT_PUBLIC_SUPABASE_ANON_KEY: ''
    _NEXT_PUBLIC_SUPABASE_PROJECT_ALL_URL: ''
    _NEXT_PUBLIC_SUPABASE_PROJECT_ALL_ANON: ''
    _NEXT_PUBLIC_SUPABASE_PROJECT_ALL_SCHEMA: ''
    _GEMINI_CLIENT_ID: ''
    _GEMINI_CLIENT_SECRET: ''
    _GEMINI_API_KEY: ''
    _APS_CLIENT_ID: ''
    _APS_CLIENT_SECRET: ''
    _APS_CALLBACK_URL: ''
    _CLAUDE_API_KEY: ''
    _GOOGLE_SERVICE_ACCOUNT_EMAIL: ''
    _GOOGLE_PRIVATE_KEY: ''
