-- Create the viz_projects table
CREATE TABLE IF NOT EXISTS public.viz_projects (
    id TEXT PRIMARY KEY, -- Using TEXT to preserve the current short IDs generated by uid()
    name TEXT NOT NULL,
    project_id TEXT NOT NULL,
    sector TEXT NOT NULL,
    studio TEXT NOT NULL,
    phase TEXT NOT NULL,
    gates JSONB NOT NULL DEFAULT '{"1": null, "2": null, "3": null, "4": null}',
    created TEXT NOT NULL
);

-- Create the viz_logs table
CREATE TABLE IF NOT EXISTS public.viz_logs (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES public.viz_projects(id) ON DELETE CASCADE,
    phase TEXT NOT NULL,
    tool TEXT NOT NULL,
    prompt TEXT NOT NULL,
    reference_inputs TEXT NOT NULL,
    output_file TEXT NOT NULL,
    status TEXT NOT NULL,
    designer TEXT NOT NULL,
    date TEXT NOT NULL,
    notes TEXT NOT NULL,
    in_library BOOLEAN NOT NULL DEFAULT false
);

-- Enable RLS
ALTER TABLE public.viz_projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.viz_logs ENABLE ROW LEVEL SECURITY;

-- Create policies for public access (since the app currently doesn't strictly isolate projects by user)
CREATE POLICY "Enable read access for all users" ON public.viz_projects FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON public.viz_projects FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON public.viz_projects FOR UPDATE USING (true);
CREATE POLICY "Enable delete for all users" ON public.viz_projects FOR DELETE USING (true);

CREATE POLICY "Enable read access for all users" ON public.viz_logs FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON public.viz_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON public.viz_logs FOR UPDATE USING (true);
CREATE POLICY "Enable delete for all users" ON public.viz_logs FOR DELETE USING (true);
